/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.mogujie.jessica.service.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SearchService
{

    public interface Iface
    {

        public SearchResponse search(SearchRequest searchRequest) throws org.apache.thrift.TException;

    }

    public interface AsyncIface
    {

        public void search(SearchRequest searchRequest, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.search_call> resultHandler) throws org.apache.thrift.TException;

    }

    public static class Client extends org.apache.thrift.TServiceClient implements Iface
    {
        public static class Factory implements org.apache.thrift.TServiceClientFactory<Client>
        {
            public Factory()
            {
            }

            public Client getClient(org.apache.thrift.protocol.TProtocol prot)
            {
                return new Client(prot);
            }

            public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot)
            {
                return new Client(iprot, oprot);
            }
        }

        public Client(org.apache.thrift.protocol.TProtocol prot)
        {
            super(prot, prot);
        }

        public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot)
        {
            super(iprot, oprot);
        }

        public SearchResponse search(SearchRequest searchRequest) throws org.apache.thrift.TException
        {
            send_search(searchRequest);
            return recv_search();
        }

        public void send_search(SearchRequest searchRequest) throws org.apache.thrift.TException
        {
            search_args args = new search_args();
            args.setSearchRequest(searchRequest);
            sendBase("search", args);
        }

        public SearchResponse recv_search() throws org.apache.thrift.TException
        {
            search_result result = new search_result();
            receiveBase(result, "search");
            if (result.isSetSuccess())
            {
                return result.success;
            }
            throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "search failed: unknown result");
        }

    }

    public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface
    {
        public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient>
        {
            private org.apache.thrift.async.TAsyncClientManager clientManager;
            private org.apache.thrift.protocol.TProtocolFactory protocolFactory;

            public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory)
            {
                this.clientManager = clientManager;
                this.protocolFactory = protocolFactory;
            }

            public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport)
            {
                return new AsyncClient(protocolFactory, clientManager, transport);
            }
        }

        public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport)
        {
            super(protocolFactory, clientManager, transport);
        }

        public void search(SearchRequest searchRequest, org.apache.thrift.async.AsyncMethodCallback<search_call> resultHandler) throws org.apache.thrift.TException
        {
            checkReady();
            search_call method_call = new search_call(searchRequest, resultHandler, this, ___protocolFactory, ___transport);
            this.___currentMethod = method_call;
            ___manager.call(method_call);
        }

        public static class search_call extends org.apache.thrift.async.TAsyncMethodCall
        {
            private SearchRequest searchRequest;

            public search_call(SearchRequest searchRequest, org.apache.thrift.async.AsyncMethodCallback<search_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException
            {
                super(client, protocolFactory, transport, resultHandler, false);
                this.searchRequest = searchRequest;
            }

            public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException
            {
                prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("search", org.apache.thrift.protocol.TMessageType.CALL, 0));
                search_args args = new search_args();
                args.setSearchRequest(searchRequest);
                args.write(prot);
                prot.writeMessageEnd();
            }

            public SearchResponse getResult() throws org.apache.thrift.TException
            {
                if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ)
                {
                    throw new IllegalStateException("Method call not finished!");
                }
                org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
                org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
                return (new Client(prot)).recv_search();
            }
        }

    }

    public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor implements org.apache.thrift.TProcessor
    {
        private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());

        public Processor(I iface)
        {
            super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
        }

        protected Processor(I iface, Map<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap)
        {
            super(iface, getProcessMap(processMap));
        }

        private static <I extends Iface> Map<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(Map<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap)
        {
            processMap.put("search", new search());
            return processMap;
        }

        private static class search<I extends Iface> extends org.apache.thrift.ProcessFunction<I, search_args>
        {
            public search()
            {
                super("search");
            }

            protected search_args getEmptyArgsInstance()
            {
                return new search_args();
            }

            protected search_result getResult(I iface, search_args args) throws org.apache.thrift.TException
            {
                search_result result = new search_result();
                result.success = iface.search(args.searchRequest);
                return result;
            }
        }

    }

    public static class search_args implements org.apache.thrift.TBase<search_args, search_args._Fields>, java.io.Serializable, Cloneable
    {
        private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("search_args");

        private static final org.apache.thrift.protocol.TField SEARCH_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("searchRequest", org.apache.thrift.protocol.TType.STRUCT, (short) 1);

        public SearchRequest searchRequest; // required

        /**
         * The set of fields this struct contains, along with convenience
         * methods for finding and manipulating them.
         */
        public enum _Fields implements org.apache.thrift.TFieldIdEnum
        {
            SEARCH_REQUEST((short) 1, "searchRequest");

            private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

            static
            {
                for (_Fields field : EnumSet.allOf(_Fields.class))
                {
                    byName.put(field.getFieldName(), field);
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, or null if its
             * not found.
             */
            public static _Fields findByThriftId(int fieldId)
            {
                switch (fieldId)
                {
                case 1: // SEARCH_REQUEST
                    return SEARCH_REQUEST;
                default:
                    return null;
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, throwing an
             * exception if it is not found.
             */
            public static _Fields findByThriftIdOrThrow(int fieldId)
            {
                _Fields fields = findByThriftId(fieldId);
                if (fields == null)
                    throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
                return fields;
            }

            /**
             * Find the _Fields constant that matches name, or null if its not
             * found.
             */
            public static _Fields findByName(String name)
            {
                return byName.get(name);
            }

            private final short _thriftId;
            private final String _fieldName;

            _Fields(short thriftId, String fieldName)
            {
                _thriftId = thriftId;
                _fieldName = fieldName;
            }

            public short getThriftFieldId()
            {
                return _thriftId;
            }

            public String getFieldName()
            {
                return _fieldName;
            }
        }

        // isset id assignments

        public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
        static
        {
            Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
            tmpMap.put(_Fields.SEARCH_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("searchRequest", org.apache.thrift.TFieldRequirementType.DEFAULT, new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchRequest.class)));
            metaDataMap = Collections.unmodifiableMap(tmpMap);
            org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(search_args.class, metaDataMap);
        }

        public search_args()
        {
        }

        public search_args(SearchRequest searchRequest)
        {
            this();
            this.searchRequest = searchRequest;
        }

        /**
         * Performs a deep copy on <i>other</i>.
         */
        public search_args(search_args other)
        {
            if (other.isSetSearchRequest())
            {
                this.searchRequest = new SearchRequest(other.searchRequest);
            }
        }

        public search_args deepCopy()
        {
            return new search_args(this);
        }

        @Override
        public void clear()
        {
            this.searchRequest = null;
        }

        public SearchRequest getSearchRequest()
        {
            return this.searchRequest;
        }

        public search_args setSearchRequest(SearchRequest searchRequest)
        {
            this.searchRequest = searchRequest;
            return this;
        }

        public void unsetSearchRequest()
        {
            this.searchRequest = null;
        }

        /**
         * Returns true if field searchRequest is set (has been assigned a
         * value) and false otherwise
         */
        public boolean isSetSearchRequest()
        {
            return this.searchRequest != null;
        }

        public void setSearchRequestIsSet(boolean value)
        {
            if (!value)
            {
                this.searchRequest = null;
            }
        }

        public void setFieldValue(_Fields field, Object value)
        {
            switch (field)
            {
            case SEARCH_REQUEST:
                if (value == null)
                {
                    unsetSearchRequest();
                } else
                {
                    setSearchRequest((SearchRequest) value);
                }
                break;

            }
        }

        public Object getFieldValue(_Fields field)
        {
            switch (field)
            {
            case SEARCH_REQUEST:
                return getSearchRequest();

            }
            throw new IllegalStateException();
        }

        /**
         * Returns true if field corresponding to fieldID is set (has been
         * assigned a value) and false otherwise
         */
        public boolean isSet(_Fields field)
        {
            if (field == null)
            {
                throw new IllegalArgumentException();
            }

            switch (field)
            {
            case SEARCH_REQUEST:
                return isSetSearchRequest();
            }
            throw new IllegalStateException();
        }

        @Override
        public boolean equals(Object that)
        {
            if (that == null)
                return false;
            if (that instanceof search_args)
                return this.equals((search_args) that);
            return false;
        }

        public boolean equals(search_args that)
        {
            if (that == null)
                return false;

            boolean this_present_searchRequest = true && this.isSetSearchRequest();
            boolean that_present_searchRequest = true && that.isSetSearchRequest();
            if (this_present_searchRequest || that_present_searchRequest)
            {
                if (!(this_present_searchRequest && that_present_searchRequest))
                    return false;
                if (!this.searchRequest.equals(that.searchRequest))
                    return false;
            }

            return true;
        }

        @Override
        public int hashCode()
        {
            return 0;
        }

        public int compareTo(search_args other)
        {
            if (!getClass().equals(other.getClass()))
            {
                return getClass().getName().compareTo(other.getClass().getName());
            }

            int lastComparison = 0;
            search_args typedOther = (search_args) other;

            lastComparison = Boolean.valueOf(isSetSearchRequest()).compareTo(typedOther.isSetSearchRequest());
            if (lastComparison != 0)
            {
                return lastComparison;
            }
            if (isSetSearchRequest())
            {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchRequest, typedOther.searchRequest);
                if (lastComparison != 0)
                {
                    return lastComparison;
                }
            }
            return 0;
        }

        public _Fields fieldForId(int fieldId)
        {
            return _Fields.findByThriftId(fieldId);
        }

        public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField field;
            iprot.readStructBegin();
            while (true)
            {
                field = iprot.readFieldBegin();
                if (field.type == org.apache.thrift.protocol.TType.STOP)
                {
                    break;
                }
                switch (field.id)
                {
                case 1: // SEARCH_REQUEST
                    if (field.type == org.apache.thrift.protocol.TType.STRUCT)
                    {
                        this.searchRequest = new SearchRequest();
                        this.searchRequest.read(iprot);
                    } else
                    {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                default:
                    org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be
            // checked in the validate method
            validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException
        {
            validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (this.searchRequest != null)
            {
                oprot.writeFieldBegin(SEARCH_REQUEST_FIELD_DESC);
                this.searchRequest.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

        @Override
        public String toString()
        {
            StringBuilder sb = new StringBuilder("search_args(");
            boolean first = true;

            sb.append("searchRequest:");
            if (this.searchRequest == null)
            {
                sb.append("null");
            } else
            {
                sb.append(this.searchRequest);
            }
            first = false;
            sb.append(")");
            return sb.toString();
        }

        public void validate() throws org.apache.thrift.TException
        {
            // check for required fields
        }

        private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException
        {
            try
            {
                write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
            } catch (org.apache.thrift.TException te)
            {
                throw new java.io.IOException(te);
            }
        }

        private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException
        {
            try
            {
                read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
            } catch (org.apache.thrift.TException te)
            {
                throw new java.io.IOException(te);
            }
        }

    }

    public static class search_result implements org.apache.thrift.TBase<search_result, search_result._Fields>, java.io.Serializable, Cloneable
    {
        private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("search_result");

        private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short) 0);

        public SearchResponse success; // required

        /**
         * The set of fields this struct contains, along with convenience
         * methods for finding and manipulating them.
         */
        public enum _Fields implements org.apache.thrift.TFieldIdEnum
        {
            SUCCESS((short) 0, "success");

            private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

            static
            {
                for (_Fields field : EnumSet.allOf(_Fields.class))
                {
                    byName.put(field.getFieldName(), field);
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, or null if its
             * not found.
             */
            public static _Fields findByThriftId(int fieldId)
            {
                switch (fieldId)
                {
                case 0: // SUCCESS
                    return SUCCESS;
                default:
                    return null;
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, throwing an
             * exception if it is not found.
             */
            public static _Fields findByThriftIdOrThrow(int fieldId)
            {
                _Fields fields = findByThriftId(fieldId);
                if (fields == null)
                    throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
                return fields;
            }

            /**
             * Find the _Fields constant that matches name, or null if its not
             * found.
             */
            public static _Fields findByName(String name)
            {
                return byName.get(name);
            }

            private final short _thriftId;
            private final String _fieldName;

            _Fields(short thriftId, String fieldName)
            {
                _thriftId = thriftId;
                _fieldName = fieldName;
            }

            public short getThriftFieldId()
            {
                return _thriftId;
            }

            public String getFieldName()
            {
                return _fieldName;
            }
        }

        // isset id assignments

        public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
        static
        {
            Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
            tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, SearchResponse.class)));
            metaDataMap = Collections.unmodifiableMap(tmpMap);
            org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(search_result.class, metaDataMap);
        }

        public search_result()
        {
        }

        public search_result(SearchResponse success)
        {
            this();
            this.success = success;
        }

        /**
         * Performs a deep copy on <i>other</i>.
         */
        public search_result(search_result other)
        {
            if (other.isSetSuccess())
            {
                this.success = new SearchResponse(other.success);
            }
        }

        public search_result deepCopy()
        {
            return new search_result(this);
        }

        @Override
        public void clear()
        {
            this.success = null;
        }

        public SearchResponse getSuccess()
        {
            return this.success;
        }

        public search_result setSuccess(SearchResponse success)
        {
            this.success = success;
            return this;
        }

        public void unsetSuccess()
        {
            this.success = null;
        }

        /**
         * Returns true if field success is set (has been assigned a value) and
         * false otherwise
         */
        public boolean isSetSuccess()
        {
            return this.success != null;
        }

        public void setSuccessIsSet(boolean value)
        {
            if (!value)
            {
                this.success = null;
            }
        }

        public void setFieldValue(_Fields field, Object value)
        {
            switch (field)
            {
            case SUCCESS:
                if (value == null)
                {
                    unsetSuccess();
                } else
                {
                    setSuccess((SearchResponse) value);
                }
                break;

            }
        }

        public Object getFieldValue(_Fields field)
        {
            switch (field)
            {
            case SUCCESS:
                return getSuccess();

            }
            throw new IllegalStateException();
        }

        /**
         * Returns true if field corresponding to fieldID is set (has been
         * assigned a value) and false otherwise
         */
        public boolean isSet(_Fields field)
        {
            if (field == null)
            {
                throw new IllegalArgumentException();
            }

            switch (field)
            {
            case SUCCESS:
                return isSetSuccess();
            }
            throw new IllegalStateException();
        }

        @Override
        public boolean equals(Object that)
        {
            if (that == null)
                return false;
            if (that instanceof search_result)
                return this.equals((search_result) that);
            return false;
        }

        public boolean equals(search_result that)
        {
            if (that == null)
                return false;

            boolean this_present_success = true && this.isSetSuccess();
            boolean that_present_success = true && that.isSetSuccess();
            if (this_present_success || that_present_success)
            {
                if (!(this_present_success && that_present_success))
                    return false;
                if (!this.success.equals(that.success))
                    return false;
            }

            return true;
        }

        @Override
        public int hashCode()
        {
            return 0;
        }

        public int compareTo(search_result other)
        {
            if (!getClass().equals(other.getClass()))
            {
                return getClass().getName().compareTo(other.getClass().getName());
            }

            int lastComparison = 0;
            search_result typedOther = (search_result) other;

            lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
            if (lastComparison != 0)
            {
                return lastComparison;
            }
            if (isSetSuccess())
            {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
                if (lastComparison != 0)
                {
                    return lastComparison;
                }
            }
            return 0;
        }

        public _Fields fieldForId(int fieldId)
        {
            return _Fields.findByThriftId(fieldId);
        }

        public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException
        {
            org.apache.thrift.protocol.TField field;
            iprot.readStructBegin();
            while (true)
            {
                field = iprot.readFieldBegin();
                if (field.type == org.apache.thrift.protocol.TType.STOP)
                {
                    break;
                }
                switch (field.id)
                {
                case 0: // SUCCESS
                    if (field.type == org.apache.thrift.protocol.TType.STRUCT)
                    {
                        this.success = new SearchResponse();
                        this.success.read(iprot);
                    } else
                    {
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                    }
                    break;
                default:
                    org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be
            // checked in the validate method
            validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException
        {
            oprot.writeStructBegin(STRUCT_DESC);

            if (this.isSetSuccess())
            {
                oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
                this.success.write(oprot);
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

        @Override
        public String toString()
        {
            StringBuilder sb = new StringBuilder("search_result(");
            boolean first = true;

            sb.append("success:");
            if (this.success == null)
            {
                sb.append("null");
            } else
            {
                sb.append(this.success);
            }
            first = false;
            sb.append(")");
            return sb.toString();
        }

        public void validate() throws org.apache.thrift.TException
        {
            // check for required fields
        }

        private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException
        {
            try
            {
                write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
            } catch (org.apache.thrift.TException te)
            {
                throw new java.io.IOException(te);
            }
        }

        private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException
        {
            try
            {
                read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
            } catch (org.apache.thrift.TException te)
            {
                throw new java.io.IOException(te);
            }
        }

    }

}
